// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebReportMessageService;

namespace WebReportMessageService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20220420192038_IncidentReportMigration")]
    partial class IncidentReportMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("WebReportMessageService.IncidentReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("AssistanceNeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AttackVector")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FixationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeOfAttack")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("WebReportMessageService.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("WebReportMessageService.MonitorAbonent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("HostName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MonitorAbonents");
                });

            modelBuilder.Entity("WebReportMessageService.MonitorMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CpuUsage")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MonitorAbonentId")
                        .HasColumnType("bigint");

                    b.Property<int>("RamUsage")
                        .HasColumnType("int");

                    b.Property<long>("ThreatId")
                        .HasColumnType("bigint");

                    b.Property<long>("Uptime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MonitorMeasurements");
                });

            modelBuilder.Entity("WebReportMessageService.NetworkResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NetworkResources");
                });

            modelBuilder.Entity("WebReportMessageService.ScanJobResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PlanNextScan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SuccessScanned")
                        .HasColumnType("int");

                    b.Property<long>("ThreatId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalResources")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScanJobResults");
                });

            modelBuilder.Entity("WebReportMessageService.ScanJobSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("JobRestartMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PingFailureThreat")
                        .HasColumnType("int");

                    b.Property<int>("PingRetries")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScanJobSettings");
                });

            modelBuilder.Entity("WebReportMessageService.Threat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateAppeared")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ThreatMessage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Threats");
                });
#pragma warning restore 612, 618
        }
    }
}
